## node configurations
node:
  ## the type of crust, for example: authority, full
  chain: "authority"
  ## enable or disable sworker
  sworker: "enable"
  ## enable or disable karst
  karst: "disable"

## identity configurations
identity:
  ## the backup of chain controller account
  backup:  ''
  ## the password of chain controller account
  password: ""

## chain configurations
chain:
  ## the name of chain node
  name: "vnode"

## sworker configurations
sworker:
  ## the srd data will be saved in those paths, need absolute path
  srd_paths:
    - "/opt/crust/data/sworker/srd1"
    - "/opt/crust/data/sworker/srd2"
  ## the number of srd in GB, input must be an integer greater than 0
  srd_init_capacity: 1

## karst configurations
karst:
  ## the thacker address
  tracker_addrs: "127.0.0.1:22122"
